### ISSUE TITLE
MYSQL을 이용하여 DB를 만들어서 연동할 생각입니다 다만...

### ISSUE THREAD

**Issue by skywings-kor** [HyunIm/BlueStar#2]
이 SQL프로그램이 사지방에 설치해도 되는지 걱정되서 일단 진행은 안하고 있습니다. SQL을 이용한 DB구축 부탁드려도 되겠습니까?

**Comment by HyunIm** [comment]
SQL 사용할 수 있는 URL을 카카오톡으로 따로 보내줄게~
